---
name: "Semantic PR and Commit Messages"

on:
  push:
    branches: [ "release-1.26" ]

jobs:
  semantic:
    uses: influxdata/validate-semantic-github-messages/.github/workflows/semantic.yml@main
    with:
      CHECK_PR_TITLE_OR_ONE_COMMIT: true

